import {expect, test} from 'vitest';
import {HDate} from '@hebcal/hdate';
import {HebrewDateEvent} from '../src/HebrewDateEvent';

test('render', () => {
  const elul29 = new HDate(29, 'Elul', 5779);
  const hd1 = new HebrewDateEvent(elul29);
  const tishrei1 = new HDate(1, 'Tishrei', 5780);
  const hd2 = new HebrewDateEvent(tishrei1);
  expect(hd1.render()).toBe('29th of Elul, 5779');
  expect(hd1.render('en')).toBe('29th of Elul, 5779');
  expect(hd1.render('')).toBe('29th of Elul, 5779');
  expect(hd1.render('s')).toBe('29th of Elul, 5779');
  expect(hd1.render('ashkenazi')).toBe('29th of Elul, 5779');
  expect(hd1.render('he')).toBe('כ״ט אֱלוּל תשע״ט');
  expect(hd1.render('he-x-NoNikud')).toBe('כ״ט אלול תשע״ט');
  expect(hd2.render()).toBe('1st of Tishrei, 5780');
  expect(hd2.render('')).toBe('1st of Tishrei, 5780');
  expect(hd2.render('en')).toBe('1st of Tishrei, 5780');
  expect(hd2.render('ashkenazi')).toBe('1st of Tishrei, 5780');
  expect(hd2.render('h')).toBe('א׳ תִּשְׁרֵי תש״פ');
  expect(hd2.render('he-x-NoNikud')).toBe('א׳ תשרי תש״פ');
  expect(elul29.render()).toBe('29th of Elul, 5779');
  expect(elul29.render('en')).toBe('29th of Elul, 5779');
  expect(elul29.render('')).toBe('29th of Elul, 5779');
  expect(elul29.render('ashkenazi')).toBe('29th of Elul, 5779');
  expect(elul29.render('he')).toBe('29 אֱלוּל, 5779');
  expect(elul29.render('he-x-NoNikud')).toBe('29 אלול, 5779');
  expect(tishrei1.render()).toBe('1st of Tishrei, 5780');
  expect(tishrei1.render('')).toBe('1st of Tishrei, 5780');
  expect(tishrei1.render('en')).toBe('1st of Tishrei, 5780');
  expect(tishrei1.render('ashkenazi')).toBe('1st of Tishrei, 5780');
  expect(tishrei1.render('he')).toBe('1 תִּשְׁרֵי, 5780');
  expect(tishrei1.render('he-x-NoNikud')).toBe('1 תשרי, 5780');
});

test('renderBrief', () => {
  const elul29ev = new HebrewDateEvent(new HDate(29, 'Elul', 5779));
  expect(elul29ev.renderBrief()).toBe('29th of Elul');
  expect(elul29ev.renderBrief('en')).toBe('29th of Elul');
  expect(elul29ev.renderBrief('s')).toBe('29th of Elul');
  expect(elul29ev.renderBrief('')).toBe('29th of Elul');
  expect(elul29ev.renderBrief('ashkenazi')).toBe('29th of Elul');
  expect(elul29ev.renderBrief('h')).toBe('כ״ט אֱלוּל');
  expect(elul29ev.renderBrief('he-x-NoNikud')).toBe('כ״ט אלול');
  const tishrei1ev = new HebrewDateEvent(new HDate(1, 'Tishrei', 5780));
  expect(tishrei1ev.renderBrief()).toBe('1st of Tishrei, 5780');
  expect(tishrei1ev.renderBrief('')).toBe('1st of Tishrei, 5780');
  expect(tishrei1ev.renderBrief('en')).toBe('1st of Tishrei, 5780');
  expect(tishrei1ev.renderBrief('ashkenazi')).toBe('1st of Tishrei, 5780');
  expect(tishrei1ev.renderBrief('he')).toBe('א׳ תִּשְׁרֵי תש״פ');
  expect(tishrei1ev.renderBrief('he-x-NoNikud')).toBe('א׳ תשרי תש״פ');
  const tishrei2ev = new HebrewDateEvent(new HDate(2, 'Tishrei', 5780));
  expect(tishrei2ev.renderBrief()).toBe('2nd of Tishrei');
  expect(tishrei2ev.renderBrief('')).toBe('2nd of Tishrei');
  expect(tishrei2ev.renderBrief('en')).toBe('2nd of Tishrei');
  expect(tishrei2ev.renderBrief('ashkenazi')).toBe('2nd of Tishrei');
  expect(tishrei2ev.renderBrief('he')).toBe('ב׳ תִּשְׁרֵי');
  expect(tishrei2ev.renderBrief('he-x-NoNikud')).toBe('ב׳ תשרי');
});
