export const holidayDescs = {
  ROSH_HASHANA_II: 'Rosh Hashana II',
  EREV_YOM_KIPPUR: 'Erev Yom Kippur',
  YOM_KIPPUR: 'Yom Kippur',
  EREV_SUKKOT: 'Erev Sukkot',
  SUKKOT_I: 'Sukkot I',
  SUKKOT_II: 'Sukkot II',
  SUKKOT_III_CHM: "Sukkot III (CH''M)",
  SUKKOT_IV_CHM: "Sukkot IV (CH''M)",
  SUKKOT_V_CHM: "Sukkot V (CH''M)",
  SUKKOT_VI_CHM: "Sukkot VI (CH''M)",
  SHMINI_ATZERET: 'Shmini Atzeret',
  SIMCHAT_TORAH: 'Simchat Torah',
  SUKKOT_VII_HOSHANA_RABA: 'Sukkot VII (Hoshana Raba)',
  CHANUKAH_1_CANDLE: 'Chanukah: 1 Candle',
  TU_BISHVAT: 'Tu BiShvat',
  EREV_PURIM: 'Erev Purim',
  PURIM: 'Purim',
  SHUSHAN_PURIM: 'Shushan Purim',
  EREV_PESACH: 'Erev Pesach',
  PESACH_I: 'Pesach I',
  PESACH_II: 'Pesach II',
  PESACH_II_CHM: "Pesach II (CH''M)",
  PESACH_III_CHM: "Pesach III (CH''M)",
  PESACH_IV_CHM: "Pesach IV (CH''M)",
  PESACH_V_CHM: "Pesach V (CH''M)",
  PESACH_VI_CHM: "Pesach VI (CH''M)",
  PESACH_VII: 'Pesach VII',
  PESACH_VIII: 'Pesach VIII',
  PESACH_SHENI: 'Pesach Sheni',
  LAG_BAOMER: 'Lag BaOmer',
  EREV_SHAVUOT: 'Erev Shavuot',
  SHAVUOT: 'Shavuot',
  SHAVUOT_I: 'Shavuot I',
  SHAVUOT_II: 'Shavuot II',
  TU_BAV: "Tu B'Av",
  ROSH_HASHANA_LABEHEMOT: 'Rosh Hashana LaBehemot',
  EREV_ROSH_HASHANA: 'Erev Rosh Hashana',
  YOM_YERUSHALAYIM: 'Yom Yerushalayim',
  BEN_GURION_DAY: 'Ben-Gurion Day',
  FAMILY_DAY: 'Family Day',
  YITZHAK_RABIN_MEMORIAL_DAY: 'Yitzhak Rabin Memorial Day',
  HERZL_DAY: 'Herzl Day',
  JABOTINSKY_DAY: 'Jabotinsky Day',
  SIGD: 'Sigd',
  YOM_HAALIYAH: 'Yom HaAliyah',
  YOM_HAALIYAH_SCHOOL_OBSERVANCE: 'Yom HaAliyah School Observance',
  HEBREW_LANGUAGE_DAY: 'Hebrew Language Day',
};
